config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    collection do
      get :search
    end
    member do
      post 'like'
    end
  end

  # resources :recipes do
  #   resources :comments, only: [:create]
  #   member do
  #     post 'like'
  #   end
  # end
  # 

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to:'chatrooms#show'

  resources :messages, only: [:create]

  # get '/recipes', to: 'recipes#index'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}
  validates :description, presence: true, length: {maximum: 2000}
  belongs_to :chef, optional: true
  validates :chef_id, presence: true

  has_many :ingredients, inverse_of: :recipe
  has_many :directions, inverse_of: :recipe
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  mount_uploader :image, ImageUploader
  default_scope -> { order(updated_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  def self.search(params)
    recipes = Recipe.includes(:ingredients).where("description LIKE ? or title LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    recipes
  end

  # def self.search(params)
  #   joins(:ingredients).where("description LIKE ? or title LIKE ? or recipe.ingredients LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
  #
  #     # .where("description = :params OR title = :params OR recipes.ingredient = :params", params: params)
  #   end
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like, :search]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]


  def index
    @recipes = Recipe.all
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end


  def new
    @recipe = Recipe.new
    # @recipe = current_chef.recipes.build
  end

  def create
    # @recipe.chef = current_chef
    # @recipe = current_chef.recipes.build(recipe_params)
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "You have successfully created a recipe"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def search
    if params[:search].blank?
      @recipes = Recipe.all
    else
      @recipes = Recipe.search(params)
    end
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe has been updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Your recipe has been deleted"
    redirect_to recipes_path
  end

  def like
    like = Like.create(like:params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_back fallback_location: 'recipes/show'
    else
      flash[:danger] = 'You can only like or dislike a recipe once'
    end
  end

  private

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end

    def require_same_user
      if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger] = 'You can only edit or delete your own recipes'
        redirect_to recipes_path
      end
    end

    def require_user_like
      if !logged_in?
        flash[:danger] = 'You must be logged in to perform that action'
        redirect_to :back
      end
    end



end

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true, class: 'form-horizontal' } do |f| %>
  <% if @recipe.errors.any? %>
    <p>
      <%= @recipe.errors.count %>
      Prevented this recipe from being saved
    </p>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>
<div class="container">
  <div class="card-body form-group col-md-10">
    <%= f.input :title, html: { class: 'form-control' } %>
    <%= f.input :description, html: { class: 'form-control' } %>
    <%= f.input :image, accept: 'image/jpeg, image/gif, image/png', input_html: { class: 'form-control', role: 'form' } %>
 
    
  

    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Step', f, :directions, class: 'btn btn-default add-button' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

    
  
  







<!--<%= simple_form_for @recipe, html: { multipart: true, class: 'form-horizontal' } do |f| %>-->
<!--  <% if @recipe.errors.any? %>-->
<!--    <p>-->
<!--      <%= @recipe.errors.count %>-->
<!--      Prevented this recipe from being saved-->
<!--    </p>-->
<!--    <ul>-->
<!--      <% @recipe.errors.full_messages.each do |msg| %>-->
<!--        <li>-->
<!--          <%= msg %>-->
<!--        </li>-->
<!--      <% end %>-->
<!--    </ul>-->
<!--  <% end %>-->
<!--<div class="container">-->
<!--  <div class="card-body form-group">-->
<!--    <%= f.input :title, html: { class: 'form-control' } %>-->
<!--    <%= f.input :description, html: { class: 'form-control' } %>-->
<!--    <%= f.input :image, accept: 'image/jpeg, image/gif, image/png', input_html: { class: 'form-control', role: 'form' } %>-->
    
<!--    <div class="row">-->
<!--      <div class="col-md-6">-->
<!--        <h3>Ingredients</h3>-->
<!--        <div id="ingredients">-->
<!--          <%= f.simple_fields_for :ingredients do |ingredient| %>-->
<!--            <%= render 'ingredient_fields', f: ingredient %>-->
<!--          <% end %>-->
<!--          <div class="links">-->
<!--            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="col-md-6">-->
<!--        <h3>Directions</h3>-->
<!--        <div id="directions">-->
<!--          <%= f.simple_fields_for :directions do |direction| %>-->
<!--            <%= render 'direction_fields', f: direction %>-->
<!--          <% end %>-->
<!--          <div class="links">-->
<!--            <%= link_to_add_association 'Add Step', f, :directions, class: 'btn btn-default add-button' %>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
    
    
<!--     <%= f.button :submit, class: "btn btn-danger" %>-->
     
    
<!--  <% end %>-->
  
<!--  <div class="col-md-4 col-md-offset-4">-->
<!--    [ <%= link_to 'Cancel request and return to Recipes', recipes_path %> ]-->
<!--  </div>-->
    
<!--  </div>-->
<!--</div>-->

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
<div class="container">
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-10 card card-body bg-light">
    <div class="recipe-img image-main double-border">
      <%= image_tag(recipe.image.url, size: '200x200', class: 'float-left img-thumbnail mr-3') if recipe.image? %>

    <!-- <section class="chef_info text-right">-->
    <!--  <%= gravatar_for(recipe.chef, size: 120) %>-->
    <!--</section>-->


    <section class='chefs-recipes'>
    <h4><%= link_to recipe.title.titleize, recipe_path(recipe), class: 'title-link pl-2' %></h4>
    <h6 class="text-muted"><%= truncate(recipe.description, length: 150, class: 'title-link') %></h6>
    <!--<small>Created <%= time_ago_in_words(recipe.created_at) %>ago by:-->
    <!-- <%= recipe.chef.chefname.titleize %></small>-->

     <p>
       <span class="quiet title-link"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.titleize %> | <%= pluralize(recipe.comments.count, 'Comment') %></small></span>
     </p>


     <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
      <div class="recipe-actions">
         <%= link_to 'Edit this recipe', edit_recipe_path(recipe), class: 'btn btn-xs btn-warning title-link' %>
         <%= link_to 'Delete this recipe', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure you want to delete this recipe?' }, class: 'btn btn-xs btn-danger title-link' %>
      </div>
    <% end %>



     <div class="row">
      <div class="col">
        <div class="float-sm-right liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="fa fa-thumbs-up fa-lg"></i>
          <% end %> <%= recipe.thumbs_up_total %> ||
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="fa fa-thumbs-down fa-lg"></i>
        <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>
    </div>
  </div>
    </section>


    </div>
  </div>




</div>
</div>

<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="container mt-5">
<%= render 'shared/page_title', title: 'All Recipes' %>



<div class="container image-container">
<% @recipes.each_slice(6) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag(recipe.image.url,size: '300x300') unless recipe.image.blank? %>
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title.titleize, recipe, class: 'title-link' %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

</div>

app/views/recipes/new.html.erb
<div class="container pt-5">
  <%= render 'shared/page_title', title: 'Create a New Recipe' %>

  <%= render 'form' %>
</div>

app/views/recipes/search.html.erb
<div class="container mt-5">
<%= render 'shared/page_title', title: 'Search Results' %>

<table class="table table-hover table-striped table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
    <tr>

      <td class="align-middle">
        <%= link_to recipe do %>
          <span class="search-recipe-link"><%= recipe.title %></span>
      </td>
      <% end %>
      <td class="align-middle">
        <%= truncate(recipe.description, length: 150) %>
      </td>
      <td>
        <%= image_tag(recipe.image.url,size: '100x100') unless recipe.image.blank? %>

      </td>

    </tr>
    <% end %>
  </tbody>
</table>





</div>

app/views/recipes/show.html.erb
<div class="show-page">
<%= render 'shared/page_title', title: @recipe.title %>

<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag(@recipe.image.url, size: '450x400') if @recipe.image? %>
    </div>
    <div class="col-md-8 col-md-offset-1">
      <div id="recipe_info">
        <h2>
          <%= @recipe.title.titleize %>
        </h2>

        <p class="description">
          <%= @recipe.description %>
        </p>
        <span class="quiet float-right"><small>Created <%= time_ago_in_words(@recipe.created_at) %> ago by: </small><em><%= @recipe.chef.chefname %></em></span>
        <p class="float-right">
          <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
        </p>

      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name.titleize %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>



      <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
        <%= link_to 'Edit', edit_recipe_path, class: 'btn btn-warning' %>
        <%= link_to 'Delete', recipe_path, method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"}, class: 'btn btn-danger' %>
      <% end %>
         <%= link_to 'Back', root_path, class: 'btn btn-success' %>
      </div>
 </div>

 <div class="container">

  <% if logged_in? %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3>Leave A Reply</h3>
        <hr />
        <%= form_for([@recipe, @comment], remote: true, :html => { class: 'form-horizontal', role: 'form' }) do |f| %>
          <div class="form-group">
            <div class="control-label col-md-2">
              <%= f.label :description, 'Comment' %>
            </div>
            <div class="col-md-12">
              <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Enter Comment Here' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              <%= f.submit "Submit Comment", class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
        <hr />
      </div>
    </div>
  <% end %>


  <div class="">
  <div class="row liking">
    <div class="row col-md-8 col-md-offset-2 pb-4">
      <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
      <i class="fa fa-thumbs-up fa-lg"></i>

      <% end %><%= @recipe.thumbs_up_total %><span class="pl-2">  || </span>
      <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
        <i class="fa fa-thumbs-down fa-lg pl-2"></i>
      <% end %> <%= @recipe.thumbs_down_total %>
    </div>
  </div>
</div>




  <% if @recipe.comments != 0 %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3>Prior Comments:</h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3>No Comments Yet!</h3>
      </div>
    </div>
  <% end %>
</div>

</div>