config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    collection do
      get :search
    end
    member do
      post 'like'
    end
  end

  # resources :recipes do
  #   resources :comments, only: [:create]
  #   member do
  #     post 'like'
  #   end
  # end
  # 

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to:'chatrooms#show'

  resources :messages, only: [:create]

  # get '/recipes', to: 'recipes#index'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'


end

app/views/layouts/_footer.html.erb
<footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
          <small class="d-block mb-3 text-muted">&copy; Shownola-2018</small>
        </div>
        <div class="col-6 col-md">
          <h5>Features</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            <li><a class="text-muted" href="#">Team feature</a></li>
            <li><a class="text-muted" href="#">Stuff for developers</a></li>
            <li><a class="text-muted" href="#">Another one</a></li>
            <li><a class="text-muted" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Another resource</a></li>
            <li><a class="text-muted" href="#">Final resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Business</a></li>
            <li><a class="text-muted" href="#">Education</a></li>
            <li><a class="text-muted" href="#">Government</a></li>
            <li><a class="text-muted" href="#">Gaming</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
          </ul>
        </div>
      </div>
    </footer>


<!-- Bootstrap core JavaScript
    <!--================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
    <!--<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>-->
    <!--<script src="../../../../assets/js/vendor/popper.min.js"></script>-->
    <!--<script src="../../../../dist/js/bootstrap.min.js"></script>-->
    <!--<script src="../../../../assets/js/vendor/holder.min.js"></script>-->
    <!--<script>-->
    <!--  Holder.addTheme('thumb', {-->
    <!--    bg: '#55595c',-->
    <!--    fg: '#eceeef',-->
    <!--    text: 'Thumbnail'-->
    <!--  });-->
    <!--</script>-->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">X</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-custom fixed-top bg-dark-gray">
  <a class="navbar-brand"><%= link_to 'Recettes de Cuisine', root_path, id: 'logo' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Create Recipe', new_recipe_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Chefs', chefs_path, class: 'nav-link' %>
      </li>

      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to 'Chatroom', chat_path, class: 'nav-link' %>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->

      <% end %>

    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

    <%= form_tag(search_recipes_path, method: :get, class: 'form-inline my-2 my-lg-0 pr-5') do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Recipes', class: 'form-control mr-sm-2' %>
      <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0 mx-0' %>
    <% end %>


     <% if logged_in? %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.titleize %>'s Profile <%= "Admin" if current_chef.admin? %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li class="dropdown-item-text"><%= link_to 'View Profile', chef_path(current_chef) %></li>
            <li class="dropdown-item-text"><%= link_to 'Edit Profile', edit_chef_path(current_chef) %></li>
            <li class="dropdown-item-text"><%= link_to 'Log out', logout_path, method: :delete, class: 'py-0 d-none d-md-inline-block' %></li>
          </div>
        </div>
      <% else %>
          <%= link_to 'Sign up', signup_path, class: 'py-0 d-none d-md-inline-block login pl-2' %>
         <%= link_to 'Log in', login_path, class: 'py-0 d-none d-md-inline-block login pl-2' %>
      <% end %>


  </div>
</nav>

app/views/layouts/application.html.erb
   <!DOCTYPE html>
<html>
  <head>
    <title>RecettesDeCuisine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>